maint: fix file name in message of findutils-check-pofiles
* Makefile.am (findutils-check-pofiles): s/configure\.in/configure.ac/,
as that file has been renamed long ago (FINDUTILS_4_3_8-1-50-gc4ef190).
While at it, re-indent the lines to shorten the lines for readability.
(coverage-clean): Re-indent likewise.
(gen-ChangeLog): While at it, replace leading blanks by a tab here for
a proper make syntax; introduced in previous commit (v4.6.0-17-g48bf0d0).

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -33,7 +33,7 @@ dist-hook: gen-ChangeLog findutils-check-pofiles findutils-check-testfiles
 .PHONY: gen-ChangeLog
 gen-ChangeLog:
 	$(AM_V_GEN)if test -d $(top_srcdir)/.git; then             \
-          $(AUXDIR)/gen-changelog.sh $(top_srcdir) > $(distdir)/cl-t \
+	  $(AUXDIR)/gen-changelog.sh $(top_srcdir) > $(distdir)/cl-t \
 	      && { rm -f $(distdir)/ChangeLog                      \
 		     && mv $(distdir)/cl-t $(distdir)/ChangeLog; } \
 	else                                                       \
@@ -42,11 +42,17 @@ gen-ChangeLog:
 	fi
 
 ## Check that we actually shipped all the .po files.  If this rule fails,
-## check ALL_LINGUAS in configure.in against the po files in the source
+## check ALL_LINGUAS in configure.ac against the po files in the source
 ## directory (their names, not their contents)
 findutils-check-pofiles:
 	@echo ; echo Checking to see if we distributed the full set of .po files
-	distcount=`ls $(distdir)/po/*.po | wc -l` ; srccount=`ls $(srcdir)/po/*.po | wc -l` ; test $$distcount -eq $$srccount || ( echo FAILED: Please check the value of ALL_LINGUAS in configure.in against the actual set of ".po" files >&2 ; false )
+	distcount=`ls $(distdir)/po/*.po | wc -l` ;                      \
+	  srccount=`ls $(srcdir)/po/*.po | wc -l` ;                      \
+	  test $$distcount -eq $$srccount                                \
+	    || { echo 'FAILED: Please check the value of ALL_LINGUAS in' \
+		   'configure.ac against the actual set of ".po" files'  \
+		   >&2 ;                                                 \
+		 false; }
 	@echo All .po files distributed OK.
 
 ## Check that we actually shipped all the test files that exist in the source.
@@ -78,6 +84,9 @@ findutils-check-smells:
 # generated by gnulib-tool and therefore we cannot add the rule to
 # those files.
 coverage-clean:
-	for dir in . gl/lib gl/lib/glthread gl/lib/uniwidth tests tests/uniwidth; do $(RM) $${dir}/*.gcno $${dir}/*.gcda $${dir}/*.gcov $${dir}/*.lcov; done
+	for dir in . gl/lib gl/lib/glthread gl/lib/uniwidth tests            \
+	  tests/uniwidth; do                                                 \
+	  $(RM) $${dir}/*.gcno $${dir}/*.gcda $${dir}/*.gcov $${dir}/*.lcov; \
+	done
 
 clean-local: coverage-clean
